import MainLayout from "@/layouts/MainLayout";
import CourseByIdView from "@/views/courses/course_id/course-by-id";
import CourseByIdDoneView from "@/views/courses/course_id/done/done";
import Head from "next/head";
import React from "react";

function CourseByIdDone() {
	return (
		<>
			<Head>
				<title>Koridorlab | Course</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<MainLayout>
        <CourseByIdDoneView />
      </MainLayout>
		</>
	);
}

export default CourseByIdDone;
