import MainLayout from "@/layouts/MainLayout";
import Head from "next/head";
import React from "react";

function Course() {
	return (
		<>
			<Head>
				<title>Koridorlab | Course</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<MainLayout>
        <div></div>
      </MainLayout>
		</>
	);
}

export default Course;
